---
name: Apache-RandomImage
version: 0.3
author:
  - 'Michael Kroell <pepl@cpan.org>'
abstract: Lightweight module to randomly display images from a directory.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  mod_perl2: 1.9922
build_requires:
  Test::More: 0
provides:
  Apache::RandomImage:
    file: lib/Apache/RandomImage.pm
    version: 0.3
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
